apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hello-app
  namespace: default
  labels:
    app:  hello-app
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  hello-app
    spec:
      containers:
      - name:  hello-app
        image:  "zapgroupdev/hello-world:latest"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
      restartPolicy: Always