apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-app-react
  labels:
    app: my-app
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: "zapgroupdev/hello-world:latest"
        ports:
        - name: web
          containerPort:  80
